{% set name = "pdal-parallelizer" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f20a5bf7e4ff2e064348801844a21b0ea6c25145713084f355f2e083a0cd1b5b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pdal-parallelizer = pdal_parallelizer.pdal_parallelizer_cli.__main__:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - click
    - dask
    - distributed
    - twine
    - pandas
    - matplotlib-base
    - pyproj
    - python-pdal

test:
  imports:
    - pdal_parallelizer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/meldig/pdal-parallelizer
  summary: A commandline app to parallelize your PDAL pipelines
  description: |
    pdal-parallelizer is a simple and complete app to parallelize
    your PDAL pipelines. With this tool, you can process a single point cloud
    or a list and start many processes.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://pdal-parallelizer.readthedocs.io
  dev_url: https://github.com/meldig/pdal-parallelizer

extra:
  recipe-maintainers:
    - ClementAlba
